### ISSUE TITLE
possible to fix the color of the splat?

### ISSUE THREAD

**Issue by JamesBotterill** [PavelDoGreat/WebGL-Fluid-Simulation#16]
I would like to have a fixed color for the splat, How would this be possible within the current version

**Comment by malik-tillman** [comment]
The multiple random splats? Or the splats instanced by input?

**Comment by JamesBotterill** [comment]
I'd be looking to explore both options

**Comment by malik-tillman** [comment]
You can go into the `generateColor` function and change the random color generation to something more static. Just note, the 3 values are in HSL (Hue, Saturation, Lightness) not RGB (Red, Green, Blue). If you want, there lives a function that converts RGB to HSL in the code as well.

**Comment by JamesBotterill** [comment]
thanks, greatly appreciated
