### ISSUE TITLE
How can i change it so it permanently "draws" instead of just of holding ?

### ISSUE THREAD

**Issue by WittiJ** [PavelDoGreat/WebGL-Fluid-Simulation#23]
Well the title already says it all i think but i mean like what do i have to Change for it to permanently draw if you hover over the site?

LG Snow

**Comment by LoopedBard3** [comment]
Quoted from @PavelDoGreat on issue [18](https://github.com/PavelDoGreat/WebGL-Fluid-Simulation/issues/18):
> [this line](https://github.com/PavelDoGreat/WebGL-Fluid-Simulation/blob/2ca3e06132f0e35cbcb016db947519be9131b4ae/script.js#L1493), move it to the bottom of a function and change it to `pointer.moved = Math.abs(pointer.deltaX) > 0 || Math.abs(pointer.deltaY) > 0;`

You will need to change this function:

> function updatePointerMoveData (pointer, posX, posY) {
    **pointer.moved = pointer.down;**
    pointer.prevTexcoordX = pointer.texcoordX;
    pointer.prevTexcoordY = pointer.texcoordY;
    pointer.texcoordX = posX / canvas.width;
    pointer.texcoordY = 1.0 - posY / canvas.height;
    pointer.deltaX = correctDeltaX(pointer.texcoordX - pointer.prevTexcoordX);
    pointer.deltaY = correctDeltaY(pointer.texcoordY - pointer.prevTexcoordY);
}

to this:

> function updatePointerMoveData (pointer, posX, posY) {
    pointer.prevTexcoordX = pointer.texcoordX;
    pointer.prevTexcoordY = pointer.texcoordY;
    pointer.texcoordX = posX / canvas.width;
    pointer.texcoordY = 1.0 - posY / canvas.height;
    pointer.deltaX = correctDeltaX(pointer.texcoordX - pointer.prevTexcoordX);
    pointer.deltaY = correctDeltaY(pointer.texcoordY - pointer.prevTexcoordY);
    **pointer.moved = Math.abs(pointer.deltaX) > 0 || Math.abs(pointer.deltaY) > 0;**
}

**Comment by PavelDoGreat** [comment]
actually you can just use `pointer.moved = true;`

**Comment by WittiJ** [comment]
thx <3

**Comment by WittiJ** [comment]
Another Little Question do you guys have a idea how i could compile this to an exe? :D

**Comment by PavelDoGreat** [comment]
google `electron`

**Comment by WittiJ** [comment]
thx <33
