### ISSUE TITLE
Error while running on chrome desktop

### ISSUE THREAD

**Issue by CageFreeFalcon** [PavelDoGreat/WebGL-Fluid-Simulation#41]
## Error while running on chrome desktop
the demo runs on all other browser but not on desktop chrome. It even runs on chrome mobile.
But works fine when i pause.
### this is the screenshot of the error
![fluid](https://user-images.githubusercontent.com/45420563/82746425-1ecee500-9dad-11ea-95fe-4f3ec96d3977.png)

**Comment by pbies** [comment]
I confirm the problems on Google Chrome.

**Comment by matthew-kaye** [comment]
Same, get the console error `[.WebGL-000001E5DB1F6550] GL_INVALID_OPERATION: Feedback loop formed between Framebuffer and active Texture.`
