### ISSUE TITLE
omnidirectional burst

### ISSUE THREAD

**Issue by ac615223s5** [PavelDoGreat/WebGL-Fluid-Simulation#94]
can you make another splat that explodes in all directions instead of moving in one

**Comment by MiracleCK** [comment]
您好，我已经收到你的信件！我会及时阅读并作出回应！

**Comment by MiracleCK** [comment]
您好，我已经收到你的信件！我会及时阅读并作出回应！

**Comment by MiracleCK** [comment]
您好，我已经收到你的信件！我会及时阅读并作出回应！
